# Generated by Django 5.1.7 on 2025-03-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WOBs',
            fields=[
                ('wob', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, default='', max_length=9)),
                ('status', models.CharField(default='Other', max_length=64)),
                ('age', models.IntegerField()),
                ('order_qty', models.IntegerField()),
                ('page_qty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'age', 'uploaded_at'], name='home_wobs_batch_33a6d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='home.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='RollBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_batches', to='home.rolls')),
            ],
            options={
                'unique_together': {('roll', 'batch')},
            },
        ),
    ]
