# Generated by Django 5.1.7 on 2025-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
