# Generated by Django 5.1.7 on 2025-03-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_old', models.IntegerField()),
                ('batch_id', models.TextField(unique=True)),
                ('mfg_batch_id', models.IntegerField()),
                ('status', models.TextField()),
                ('order_qty', models.IntegerField()),
                ('page_qty', models.IntegerField()),
            ],
        ),
    ]
