# Generated by Django 5.1.7 on 2025-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wob', models.TextField(unique=True)),
                ('batch', models.IntegerField(null=True)),
                ('status', models.TextField()),
                ('age', models.IntegerField()),
                ('order_qty', models.IntegerField()),
                ('page_qty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
    ]
