# Generated by Django 5.1.7 on 2025-03-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customeraging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomerAging',
            new_name='WOBs',
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='home.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='RollBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_batches', to='home.rolls')),
            ],
            options={
                'unique_together': {('roll', 'batch')},
            },
        ),
    ]
